# General Jekyll Config


highlighter: rouge
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

plugins:
  - jekyll-seo-tag
  
  # Google Analytics
google_analytics: UA-69432205-2


